### PR TITLE
This implements the Over operator, and includes some necessary structs and utilities.

### PR DESCRIPTION
**Pull request by bobbyesh**
# Overview
This branch includes the Over operator, the Operator enum, an Rgba struct, and some utilities for working with these tools.  The only public facing entity in the module is the Operator enum, because it will be used by users when they call the Cairus analog to `cairo_set_operator()`.  Besides that, the other things will only be used internally.

The `fetch_operator` function is just a function that takes an Operator enum and returns the operator function.  This will make for an easy way for Contexts to take their enum and get the right function, and a quick way to add new operators as we need them.

# Concerns
The Rgba struct likely belongs in a different location (likely where surface or surface formats are defined).  I think the Rgba struct makes these low level operations more readable, as opposed to a Tuple Struct or just a Tuple, but I could see the argument for using a primitive instead.  (Speed?)

# Design Choices
The compositors are in their own module because I assumed there will be a lot more to come, and they are almost purely math so form a nice isolated set of of functions.

I tried to make the destination Rgba non-mutable, but when I experimented with modifying a vector of vectors, I found that it was more or less becoming an elaborate Rube Goldberg machine, assuming we don't want every operation to require an entirely new surface to be recreated (think of changing just a 100 pixels on a 1000x1000 surface).  I do think there is an argument to made for making Cairus as stateless as possible, so I think this point is debatable.

# Todo (before merge)
I still need to include the appropriate license headers before this is ready for a merge.

### CODE REVIEW

**Comment by bobbyesh** [comment]
Added licenses to lib.rs and compositor.rs.

**Comment by bobbyesh** [comment]
I did notice that Cairo C implements the correct() functionality in the cairo_set_source_rgba() function, using _cairo_restrict_value(), which does exactly what correct() does with min and max.  When that gets implemented, we may want to remove the correct() call in new(), avoiding a call per pixel.

**Comment by ferdousi** [comment]
I was wondering if we need any loops in the "over" operator. I am still learning Rust, therefore, not 100% sure what is happening in the over operator code. But I believe we need some sort of loop to composite each pixel. Specially in the over function (fn over).  Another thing I was wondering is do we need this equation 

(source_color * source_alpha) +
        (destination_color * destination_alpha * (1. - source_alpha))

for all the red, green and blue colors.

**Comment by ferdousi** [comment]
One more thing, do we need to check if source and destination surface are the same size? Like checking if source height and width matches the destination width and height.

**Comment by bobbyesh** [comment]
About the loop, this only implements the operator itself, with two pixels as operands, but doesn't implement the application of the operator to any surface.  Since determining where to actually apply the operator is affected by things like masks and clipping, the loop will likely be in whatever function is calling the operator instead of inside the operator itself.   I would expect this to be paint() or stroke() or whatever.  That is at least my thinking on it.

**Comment by bobbyesh** [comment]
Unfortunately that equation does need to be applied to reach color element in each pixel, otherwise the omitted colors will just result in the original destination colod.  And as for the size thing, I'm not sure.  In Cairo C the context simply holds one Rgba value in the gstate struct, so I'd figure that bounds checking and stuff does get implemented elsewhere (whether that single Rgba gets painted over the whole destination or if it is used to create one single colored source surface that then gets blended onto the destination, I'm not sure), for paint() I believe the actual application of source on destination is in pixman_fill().  I don't think we'll need to go with the original implementation initially though as it uses linear algebra magic and something called matrix affinity, which I'd vote on us eventually doing but is probably beyond the needs of the MVC imho.

**Comment by bobbyesh** [comment]
Excuse my typing, I'm currently without a computer so typing this on a phone.

**Comment by bobbyesh** [comment]
I renamed compositor to operators.  I thought it would be a better handle for users.

**Comment by bobbyesh** [comment]
I noticed that std has a "std::String::into_bytes() -> Vec<u8>" function, so I changed to_int to into_bytes(), and had a return Vec<u8> instead of (u8, u8, u8, u8) to better reflect the Rust norm.

**Comment by bobbyesh** [comment]
> Compositing (why pre-multiplied alpha is the one true way).

A quote from a description of presentation slides of "An Insider's Guide to Cairo", by Carl Worth at https://cworth.org/talks/

After further research, I found that post-multiplied compositing in some cases results in the wrong value!

This needs to be re-implemented with pre-multiplied alpha compositing instead of post-.

The rationale for why Cairo uses pre-multiplied:
https://lists.cairographics.org/archives/cairo/2005-September/005355.html

**Comment by bobbyesh** [comment]
out of date, closed.

**Pull request closed without merging**
