### PR TITLE
Debug utils

### PR DESCRIPTION
**Pull request by bobbyesh**
- IntoPixels Trait, for anything that can be converted to pixels
- Impl IntoPixels for Trapezoid and LineSegment
- Added the debug_render! macro for rendering any Vec<T: IntoPixels> to a .png
- Fixed the vertical line segment rasterization bug
- Made surface::get_mut() return an Option<&mut Rgba> instead of just an &mut Rgba
- Changed all `fn into_pixel_coordinates` to `fn into_pixels` impl of `IntoPixels` trait

### CODE REVIEW

**Comment by bobbyesh** [comment]
I changed the macro to only require the `Vec<LineSegment>` and the color that you want it to be.  It'll automatically create the png size.

It puts the images in `/target/debug/images` instead of root, just so we don't have to manually delete images to keep them out of the repo and other nonsense.

**Comment by bobbyesh** [comment]
And I apparently I fixed some naming stuff in common_geometry.

**Comment by bobbyesh** [comment]
And made a build a script to build the images directory when the debug-tesselator feature is set.

**Comment by kneitinger** [comment]
👏

**Pull request merged**
